stages:
  - build
  - test

default:
  services:
    - docker:stable-dind
  before_script:
    - apk add bash make

build:
  stage: build
  only:
    - master
    - develop
    - merge_requests
  script: make build

unit-test:
  stage: test
  only:
    - master
    - develop
    - merge_requests
  script: make test
